name: learners_choice_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.2
  equatable: ^2.0.5
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_cache_manager: ^3.3.2

  google_fonts: ^6.1.0
  image_picker: ^1.1.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Images/namescreen/
    - assets/Images/imagescreen/
    - assets/Images/homescreen/
    - assets/avatars/
    - assets/Images/docsscreen/
    - assets/Images/
    - assets/icons/
    - assets/output.json
    - assets/actsData.json
    - assets/filtered_questions_with_images.json
   

    
    
