name: learners_choice_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Images/namescreen/
    - assets/Images/imagescreen/
    - assets/Images/homescreen/
    - assets/avatars/
    - assets/Images/docsscreen/
    - assets/Images/
    - assets/icons/
   

    
    
